<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>PREACT</RootNamespace>
    <BaseOutputPath>..\..\WUInity\Assets\PREACT\</BaseOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Source\Traffic\Modules\SUMO\Build_notes.txt" />
    <Content Include="Source\Traffic\Modules\SUMO\version_info.txt" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="GDAL" Version="3.11.3" />
    <PackageReference Include="GDAL.Native" Version="3.11.3" />
    <PackageReference Include="ILGPU" Version="1.5.3" />
    <PackageReference Include="ILGPU.Algorithms" Version="1.5.3" />
    <PackageReference Include="Itinero" Version="1.5.1" />
    <PackageReference Include="Itinero.IO.Osm" Version="1.5.1" />
    <PackageReference Include="System.Text.Json" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="kPERILcore">
      <HintPath>..\..\..\kperil\kPERILcore\bin\Release\netstandard2.1\kPERILcore.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Update="ThirdParty\Behave\x64\Behave.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ThirdParty\Behave\x64\BehaveCore.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ThirdParty\CityFlow\x64\CityFlow.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ThirdParty\FOFEM\x64\FOFEM.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ThirdParty\kPERIL\kPERILcore.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
