//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace SUMO {

public class TraCINextStopDataVector : TraCIResult {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal TraCINextStopDataVector(global::System.IntPtr cPtr, bool cMemoryOwn) : base(libsumoPINVOKE.TraCINextStopDataVector_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(TraCINextStopDataVector obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          libsumoPINVOKE.delete_TraCINextStopDataVector(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public override string getString() {
    string ret = libsumoPINVOKE.TraCINextStopDataVector_getString(swigCPtr);
    if (libsumoPINVOKE.SWIGPendingException.Pending) throw libsumoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public TraCINextStopDataVector2 value {
    set {
      libsumoPINVOKE.TraCINextStopDataVector_value_set(swigCPtr, TraCINextStopDataVector2.getCPtr(value));
      if (libsumoPINVOKE.SWIGPendingException.Pending) throw libsumoPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      global::System.IntPtr cPtr = libsumoPINVOKE.TraCINextStopDataVector_value_get(swigCPtr);
      TraCINextStopDataVector2 ret = (cPtr == global::System.IntPtr.Zero) ? null : new TraCINextStopDataVector2(cPtr, false);
      if (libsumoPINVOKE.SWIGPendingException.Pending) throw libsumoPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public TraCINextStopDataVector() : this(libsumoPINVOKE.new_TraCINextStopDataVector(), true) {
    if (libsumoPINVOKE.SWIGPendingException.Pending) throw libsumoPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
