//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace SUMO {

public class TraCIBestLanesVector : global::System.IDisposable, global::System.Collections.IEnumerable, global::System.Collections.Generic.IEnumerable<TraCIBestLanesData>
 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal TraCIBestLanesVector(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(TraCIBestLanesVector obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~TraCIBestLanesVector() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          libsumoPINVOKE.delete_TraCIBestLanesVector(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public TraCIBestLanesVector(global::System.Collections.IEnumerable c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (TraCIBestLanesData element in c) {
      this.Add(element);
    }
  }

  public TraCIBestLanesVector(global::System.Collections.Generic.IEnumerable<TraCIBestLanesData> c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (TraCIBestLanesData element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public TraCIBestLanesData this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < size())
        throw new global::System.ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

  public void CopyTo(TraCIBestLanesData[] array)
  {
    CopyTo(0, array, 0, this.Count);
  }

  public void CopyTo(TraCIBestLanesData[] array, int arrayIndex)
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

  public void CopyTo(int index, TraCIBestLanesData[] array, int arrayIndex, int count)
  {
    if (array == null)
      throw new global::System.ArgumentNullException("array");
    if (index < 0)
      throw new global::System.ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new global::System.ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new global::System.ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new global::System.ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new global::System.ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

  public TraCIBestLanesData[] ToArray() {
    TraCIBestLanesData[] array = new TraCIBestLanesData[this.Count];
    this.CopyTo(array);
    return array;
  }

  global::System.Collections.Generic.IEnumerator<TraCIBestLanesData> global::System.Collections.Generic.IEnumerable<TraCIBestLanesData>.GetEnumerator() {
    return new TraCIBestLanesVectorEnumerator(this);
  }

  global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() {
    return new TraCIBestLanesVectorEnumerator(this);
  }

  public TraCIBestLanesVectorEnumerator GetEnumerator() {
    return new TraCIBestLanesVectorEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class TraCIBestLanesVectorEnumerator : global::System.Collections.IEnumerator
    , global::System.Collections.Generic.IEnumerator<TraCIBestLanesData>
  {
    private TraCIBestLanesVector collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public TraCIBestLanesVectorEnumerator(TraCIBestLanesVector collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public TraCIBestLanesData Current {
      get {
        if (currentIndex == -1)
          throw new global::System.InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new global::System.InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new global::System.InvalidOperationException("Collection modified.");
        return (TraCIBestLanesData)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object global::System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new global::System.InvalidOperationException("Collection modified.");
      }
    }

    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
  }

  public void Clear() {
    libsumoPINVOKE.TraCIBestLanesVector_Clear(swigCPtr);
    if (libsumoPINVOKE.SWIGPendingException.Pending) throw libsumoPINVOKE.SWIGPendingException.Retrieve();
  }

  public void Add(TraCIBestLanesData x) {
    libsumoPINVOKE.TraCIBestLanesVector_Add(swigCPtr, TraCIBestLanesData.getCPtr(x));
    if (libsumoPINVOKE.SWIGPendingException.Pending) throw libsumoPINVOKE.SWIGPendingException.Retrieve();
  }

  private uint size() {
    uint ret = libsumoPINVOKE.TraCIBestLanesVector_size(swigCPtr);
    if (libsumoPINVOKE.SWIGPendingException.Pending) throw libsumoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private uint capacity() {
    uint ret = libsumoPINVOKE.TraCIBestLanesVector_capacity(swigCPtr);
    if (libsumoPINVOKE.SWIGPendingException.Pending) throw libsumoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void reserve(uint n) {
    libsumoPINVOKE.TraCIBestLanesVector_reserve(swigCPtr, n);
    if (libsumoPINVOKE.SWIGPendingException.Pending) throw libsumoPINVOKE.SWIGPendingException.Retrieve();
  }

  public TraCIBestLanesVector() : this(libsumoPINVOKE.new_TraCIBestLanesVector__SWIG_0(), true) {
    if (libsumoPINVOKE.SWIGPendingException.Pending) throw libsumoPINVOKE.SWIGPendingException.Retrieve();
  }

  public TraCIBestLanesVector(TraCIBestLanesVector other) : this(libsumoPINVOKE.new_TraCIBestLanesVector__SWIG_1(TraCIBestLanesVector.getCPtr(other)), true) {
    if (libsumoPINVOKE.SWIGPendingException.Pending) throw libsumoPINVOKE.SWIGPendingException.Retrieve();
  }

  public TraCIBestLanesVector(int capacity) : this(libsumoPINVOKE.new_TraCIBestLanesVector__SWIG_2(capacity), true) {
    if (libsumoPINVOKE.SWIGPendingException.Pending) throw libsumoPINVOKE.SWIGPendingException.Retrieve();
  }

  private TraCIBestLanesData getitemcopy(int index) {
    TraCIBestLanesData ret = new TraCIBestLanesData(libsumoPINVOKE.TraCIBestLanesVector_getitemcopy(swigCPtr, index), true);
    if (libsumoPINVOKE.SWIGPendingException.Pending) throw libsumoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private TraCIBestLanesData getitem(int index) {
    TraCIBestLanesData ret = new TraCIBestLanesData(libsumoPINVOKE.TraCIBestLanesVector_getitem(swigCPtr, index), false);
    if (libsumoPINVOKE.SWIGPendingException.Pending) throw libsumoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, TraCIBestLanesData val) {
    libsumoPINVOKE.TraCIBestLanesVector_setitem(swigCPtr, index, TraCIBestLanesData.getCPtr(val));
    if (libsumoPINVOKE.SWIGPendingException.Pending) throw libsumoPINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(TraCIBestLanesVector values) {
    libsumoPINVOKE.TraCIBestLanesVector_AddRange(swigCPtr, TraCIBestLanesVector.getCPtr(values));
    if (libsumoPINVOKE.SWIGPendingException.Pending) throw libsumoPINVOKE.SWIGPendingException.Retrieve();
  }

  public TraCIBestLanesVector GetRange(int index, int count) {
    global::System.IntPtr cPtr = libsumoPINVOKE.TraCIBestLanesVector_GetRange(swigCPtr, index, count);
    TraCIBestLanesVector ret = (cPtr == global::System.IntPtr.Zero) ? null : new TraCIBestLanesVector(cPtr, true);
    if (libsumoPINVOKE.SWIGPendingException.Pending) throw libsumoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, TraCIBestLanesData x) {
    libsumoPINVOKE.TraCIBestLanesVector_Insert(swigCPtr, index, TraCIBestLanesData.getCPtr(x));
    if (libsumoPINVOKE.SWIGPendingException.Pending) throw libsumoPINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, TraCIBestLanesVector values) {
    libsumoPINVOKE.TraCIBestLanesVector_InsertRange(swigCPtr, index, TraCIBestLanesVector.getCPtr(values));
    if (libsumoPINVOKE.SWIGPendingException.Pending) throw libsumoPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    libsumoPINVOKE.TraCIBestLanesVector_RemoveAt(swigCPtr, index);
    if (libsumoPINVOKE.SWIGPendingException.Pending) throw libsumoPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    libsumoPINVOKE.TraCIBestLanesVector_RemoveRange(swigCPtr, index, count);
    if (libsumoPINVOKE.SWIGPendingException.Pending) throw libsumoPINVOKE.SWIGPendingException.Retrieve();
  }

  public static TraCIBestLanesVector Repeat(TraCIBestLanesData value, int count) {
    global::System.IntPtr cPtr = libsumoPINVOKE.TraCIBestLanesVector_Repeat(TraCIBestLanesData.getCPtr(value), count);
    TraCIBestLanesVector ret = (cPtr == global::System.IntPtr.Zero) ? null : new TraCIBestLanesVector(cPtr, true);
    if (libsumoPINVOKE.SWIGPendingException.Pending) throw libsumoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    libsumoPINVOKE.TraCIBestLanesVector_Reverse__SWIG_0(swigCPtr);
    if (libsumoPINVOKE.SWIGPendingException.Pending) throw libsumoPINVOKE.SWIGPendingException.Retrieve();
  }

  public void Reverse(int index, int count) {
    libsumoPINVOKE.TraCIBestLanesVector_Reverse__SWIG_1(swigCPtr, index, count);
    if (libsumoPINVOKE.SWIGPendingException.Pending) throw libsumoPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, TraCIBestLanesVector values) {
    libsumoPINVOKE.TraCIBestLanesVector_SetRange(swigCPtr, index, TraCIBestLanesVector.getCPtr(values));
    if (libsumoPINVOKE.SWIGPendingException.Pending) throw libsumoPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
